title = "The Flix Blog"
theme = "tabi"
base_url = "https://blog.flix.dev/"
compile_sass = true
build_search_index = false

taxonomies = [
    {name = "tags", feed = true},
    {name = "authors", feed = true}
]

[extra]
show_author = true
favicon = "favicon.png"
favicon_emoji = "F"
menu = [
    { name = "blog", url = "blog", trailing_slash = true },
    { name = "tags", url = "tags", trailing_slash = true },
]
stylesheets = ["highlight.css"]
highlightjs = "highlight.js"

[markdown]
highlight_code = true
