name: Build

on: [ push, pull_request, merge_group ]

permissions:
  contents: read

# Cancel previous runs if the PR is updated
concurrency:
  cancel-in-progress: true
  group: build-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Show repo tree
        run: tree .
